main.yml: Fixes the creation of documentation
fix

Warning, treated as error:
/home/runner/work/nuttx-website/nuttx-website/nuttx/Documentation/_tags/arch-arm64.rst:6:toctree contains reference to nonexisting document 'platforms/arm64/imx9/boards/imx93-evk/index'
make: *** [Makefile:45: html] Error 2
Error: Process completed with exit code 2.

The error seems to be due to the construction order

12.1.0 -> 12.10.0 -> 12.2.0

==> BUILD NUTTX DOCUMENTATION FOR: 10.0.0,10.0.1,10.1.0,10.2.0,10.3.0,11.0.0,12.0.0,12.1.0,12.10.0,12.2.0,12.2.1,12.3.0,12.4.0,12.5.0,12.5.1,12.6.0,12.7.0,12.8.0,12.9.0 (and master).

Bump actions/checkout@v4 and actions/setup-python@v5